### ISSUE TITLE
can't download model parameter.

### ISSUE THREAD

**Issue by gucasbrg** [gyglim/video2gif_code#5]
I can't model parameter from below address ,can I get these files in the other path?
```
!wget https://data.vision.ee.ethz.ch/gyglim/C3D/c3d_model.pkl -P ./data -nc
!wget https://data.vision.ee.ethz.ch/gyglim/C3D/snipplet_mean.npy -P ./data -nc

# Get the video2gif weights
!wget https://data.vision.ee.ethz.ch/cvl/video2gif/model/video2gif_weights.npz  -P ./data -nc
    
# Finally, we also get an example video
!wget https://data.vision.ee.ethz.ch/cvl/video2gif/nWHIHe-rjoU.mp4 -P ./data -nc
```

**Comment by samlaujw** [comment]
Hi, I'm facing the same issue of not being able to download the model parameters. Any other way I can get it? Thanks!

**Comment by gyglim** [comment]
Hi

I re-uploaded the C3D data:
Model: 
https://drive.google.com/open?id=12J5Rsz3zBp3gKKvrmRU3B8s9OTAcfR7C

Snippet mean:
https://drive.google.com/open?id=1oKN5APlKzf70X4l4K4CIcuOUfbUCdHUt

The other links still work

**Comment by vitorio** [comment]
It's a year later and the weights and example video links are no longer reachable, and the Internet Archive Wayback Machine doesn't have archive copies, either.  @gyglim, are you able to provide copies of the other two links as well?
