### ISSUE TITLE
Weights file and example video no longer accessible

### ISSUE THREAD

**Issue by vitorio** [gyglim/video2gif_code#9]
The weights and example video links are no longer reachable (403 from `data.vision.ee.ethz.ch`), and the Internet Archive Wayback Machine doesn't have archive copies, either.  @gyglim, are you able to provide copies of these, as you provided Drive links in #5?

**Comment by arianaa30** [comment]
Hi I have the same problem. Can you provide the files?

**Comment by gyglim** [comment]
Works for me. Can you retry?
For backup, you can also find them here now:
Weights: https://drive.google.com/file/d/1Qvd6xXucwiis0bqlcoHB6pMIh7GXgdvK/view?usp=sharing
Video: https://drive.google.com/file/d/17LdWCqUBy0-4uXLxbw9RSUH_fGTQAbVQ/view?usp=sharing
